### GENERAL SETTINGS ###

# Site settings
title: GS Open Lab
description: "Open Source  @ GS Lab"
analytics: UA-50546869-2
baseurl: "" #important: start with /
url: "http://gslabdev.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#101931" #"#FFC12D" #"#F70031"
  primary_rgb: "16,25,49" #"255,193,45" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#757b7f" #"#33004D"
  link: "#428bca"
  link_hover: "#101931"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: linkedin
    url: https://www.linkedin.com/company/gs-lab
  - title: facebook
    url: https://www.facebook.com/LifeAtGSLab
  - title: twitter
    url: https://twitter.com/_gslab

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Amar Arma Genesis,
    - Baner Road, Baner,
    - Pune 411045 India,
email: info@gslab.com
tel: +91 20 4671 1000


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Vinod Borole
    text: Member of ContainX org (Asia) responsible for managing openstack4j contributions.
    img: Vinod_Borole_new.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vinod.borole@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/vinodborole
  - name: Shital Patil
    text: Frequent committer for openstack4j project.
    img: Shital_Patil_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:shital.patil@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/shital-patil89
  - name: Sumit Gandhi
    text: Frequent committer for openstack4j project.
    img: Sumit_Gandhi_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sumit.gandhi@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/sumit-gandhi-405b7291
  - name: Abdul Waheed
    text: Frequent committer for OTP Manager project.
    img: Abdul_Waheed_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:abdul.waheed@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/waheedabdul
  - name:	Bhumika Bayani
    text: Frequent committer for Docker project.
    img: Bhumika_Bayani_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:bhumika.bayani@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/bhumikabayani
  - name: Milind Chawre
    text: Frequent committer for Docker project.
    img: Milind_Chawre_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:milind.chawre@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/milind-chawre
  - name: Dattatraya Kumbhar
    text: Frequent committer for Docker project.
    img: Dattatraya_Kumbhar_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:dattatraya.kumbhar@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/dattatraya-kumbhar-45923a38
  - name: Manuwela Kanade
    text: Frequent committer for Apache Mesos project.
    img: Manuwela_Kanade_.jpg
    social:
      - title: envelope #use for email address
        url: mailto:manuwela.kanade@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/manuwela-kanade-526a3ab
  - name: Satish Bhor
    text: Author and committer for PepperBox project.
    img: satish_bhor_new.jpg
    social:
      - title: envelope #use for email address
        url: mailto:satish.bhor@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/satish-bhor-76589630
  - name: Nachiket Kate
    text: Author and committer for PepperBox project.
    img: Nachiket-Kate.jpg
    social:
      - title: envelope #use for email address
        url: mailto:nachiket.kate@gslab.com
      - title: linkedin
        url: https://in.linkedin.com/in/nachiketkate
  - name: Aarti Karve
    text: Committer for ScaleArc Mysql Performance benchmark Project.
    img: Aarti-Karve.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aarti.karve@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/aarti-karve-27a63014/
  - name: Basant Kumar
    text: Committer for Openstack Addon for Splunk Project.
    img: basant-kumar.jpg
    social:
      - title: envelope #use for email address
        url: mailto:basant.kumar@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/basant-kumar-74144490
  - name: Vikas Sanap
    text: Committer for Openstack App for Splunk Project.
    img: Vikas_sanap.jpg
    social:
      - title: envelope #use for email address
        url: mailto:vikas.sanap@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/vikassanap/
  - name: Ravindra Yadav
    text: Committer for StackStorm Exchange Project.
    img: ravindra_yadav.png
    social:
      - title: envelope #use for email address
        url: mailto:ravindra.yadav@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/ravindra-yadav-35576214
  - name: Yugendra Khonde
    text: Committer for StackStorm Exchange Project.
    img: yugendra_khonde.jpg
    social:
      - title: envelope #use for email address
        url: mailto:Yugendra.khonde@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/yugendra-khonde-8577a216
  - name: Aditi Kulkarni
    text: Committer for StackStorm Exchange Project.
    img: aditi_kulkarni.jpg
    social:
      - title: envelope #use for email address
        url: mailto:aditi.kulkarni@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/aditi-kulkarni-5814368b
  - name: Omkareshwar Telee
    text: Committer for Openstack Project.
    img: omkareshwar_telee.jpg
    social:
      - title: envelope #use for email address
        url: mailto:omkareshwar.telee@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/omkareshwar-telee
  - name: Bhushan Rane
    text: Committer for Terraform Provider Project.
    img: Bhushan_Rane.jpg
    social:
      - title: envelope #use for email address
        url: mailto:bhushan.rane@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/bhushan-rane-27168419/
  - name: Sadhana Sonawa
    text: Committer for Terraform Provider Project.
    img: Sadhana_Sonawa.jpg
    social:
      - title: envelope #use for email address
        url: mailto:sadhana.sonawa@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/sadhana-sonawa-8b25a06b/
  - name: Shubham Tholiya
    text: Committer for Terraform Provider Project.
    img: Shubham_Tholiya.jpg
    social:
      - title: envelope #use for email address
        url: mailto:shubham.tholiya@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/shubham-tholiya/
  - name: Kiran Gund
    text: Committer for Terraform Provider Project.
    img: Kiran_Gund.jpg
    social:
      - title: envelope #use for email address
        url: mailto:kiran.gund@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/kiran-gund-4482bb12a/
  - name: Payal Rahatal
    text: Committer for Terraform Provider Project.
    img: Payal_Rahatal.jpg
    social:
      - title: envelope #use for email address
        url: mailto:payal.rahatal@gslab.com
      - title: linkedin
        url: https://www.linkedin.com/in/payal-rahatal-4b85bb119/
      
        

# Clients information. Shown on Home and About pages.
clients:
  - name:
    img:

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "GS Lab is committed to open source technology and the commitment to collaboration is innate in our DNA. GSOpenLab is committed to drive the growth of open source technologies with its efforts on community-led initiatives, collaborations and industry focused open source code development."

# Testimonial content. Shown on Home and About page.
testimonial:
    message:
    author:
    position:
